# Generated by Django 5.1.4 on 2025-02-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_dailysale_closed_day'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
